#!/usr/bin/env ruby

require "readline"

def prompt(_prompt = "> ")
	Readline.readline(_prompt, true).squeeze(" ").strip.downcase
end

def symbol_for_direction(input)
	text = case input.downcase
	when "north", "east", "south", "west", "up", "down"
		input[0]
	when /^north ?east$/
		"ne"
	when /^north ?west$/
		"nw"
	when /^south ?east$/
		"se"
	when /^south ?west$/
		"sw"
	else
		input
	end
	text.to_sym
end


require_relative "lib/colors"
require_relative "lib/game_entity"
require_relative "lib/object_manager"
require_relative "lib/item"
require_relative "lib/scene"
require_relative "lib/scene_manager"
require_relative "lib/player"
require_relative "lib/controller"

save_file = File.expand_path("~/.peripeteia_save")
$developer_mode = false
should_delete_save_file = false

until ARGV.empty?
	case o = ARGV.shift
	when "-d", "--dev-mode"
		$developer_mode = true
	when "-l", "--load"
		save_file = File.expand_path(ARGV.shift)
	when "-r", "--reset"
		should_delete_save_file = true
	else
		puts "unrecognized option: #{o}"
		exit
	end
end

if should_delete_save_file && File.file?(save_file)
	File.delete(save_file)
end

if File.file?(save_file)
	f = File.open(save_file, "r")
	controller = Marshal.load(f.read)
	controller.save_file = save_file
else
	controller = Controller.new(save_file)
end

loop do
	💬 = prompt
	controller.handle_input(💬)
end
